sources:
  - name: CafeF
    base_urls:
      - "https://cafef.vn/thi-truong-chung-khoan.chn"
    pagination:
      type: query
      param: "p"
      start: 1
      stop: 8
    list_selector: "a[href]"
    allow_pattern: ".chn"
    date_selectors:
      - "meta[property='article:published_time']::content"
      - "time::datetime"
      - "span[class*=date]"
    content_selectors:
      - "article"
      - "div[class*=content]"
  - name: Vietstock
    base_urls:
      - "https://vietstock.vn/chung-khoan.htm"
    pagination:
      type: query
      param: "page"
      start: 1
      stop: 8
    list_selector: "a[href]"
    allow_regex: '/\d{4}/\d{2}/.+\.htm'
    url_date_regex: '/(\d{4})/(\d{2})/(\d{2})/'
    content_selectors:
      - "article"
      - "div[id*=detail], div[class*=content]"
